export const GET_GENRES_LIST_REQUEST = 'GET_GENRES_LIST_REQUEST';
export const GET_GENRES_LIST_SUCCESS = 'GET_GENRES_LIST_SUCCESS';
export const GET_GENRES_LIST_FAILURE = 'GET_GENRES_LIST_FAILURE';

export const CREATE_GENRE_REQUEST = 'CREATE_GENRE_REQUEST';
export const CREATE_GENRE_SUCCESS = 'CREATE_GENRE_SUCCESS';
export const CREATE_GENRE_FAILURE = 'CREATE_GENRE_FAILURE';

export const UPDATE_GENRE_REQUEST = 'UPDATE_GENRE_REQUEST';
export const UPDATE_GENRE_SUCCESS = 'UPDATE_GENRE_SUCCESS';
export const UPDATE_GENRE_FAILURE = 'UPDATE_GENRE_FAILURE';
